-- MySQL Script generated by MySQL Workbench
-- Thu Apr 27 21:07:44 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema diplomatic_war
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema diplomatic_war
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diplomatic_war` DEFAULT CHARACTER SET utf8 ;
USE `diplomatic_war` ;

-- -----------------------------------------------------
-- Table `diplomatic_war`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diplomatic_war`.`users` ;

CREATE TABLE IF NOT EXISTS `diplomatic_war`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_type` VARCHAR(45) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `birth_date` DATETIME NULL,
  `display_name` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `status` INT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diplomatic_war`.`passwords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diplomatic_war`.`passwords` ;

CREATE TABLE IF NOT EXISTS `diplomatic_war`.`passwords` (
  `user_id` INT NOT NULL,
  `salt` VARCHAR(255) NOT NULL,
  `password_hashed` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_passwords_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `diplomatic_war`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diplomatic_war`.`login_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diplomatic_war`.`login_history` ;

CREATE TABLE IF NOT EXISTS `diplomatic_war`.`login_history` (
  `user_id` INT NOT NULL,
  `latest_login_ip` VARCHAR(70) NULL,
  `latest_login_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `prev_login_ip` VARCHAR(70) NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_loginHistory_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `diplomatic_war`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diplomatic_war`.`sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diplomatic_war`.`sessions` ;

CREATE TABLE IF NOT EXISTS `diplomatic_war`.`sessions` (
  `user_id` INT NOT NULL,
  `session_id` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(255) NOT NULL,
  `session_hash` VARCHAR(255) NOT NULL,
  `expiry` DATETIME NOT NULL,
  PRIMARY KEY (`session_id`),
  CONSTRAINT `fk_sessions_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `diplomatic_war`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diplomatic_war`.`verifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diplomatic_war`.`verifications` ;

CREATE TABLE IF NOT EXISTS `diplomatic_war`.`verifications` (
  `user_id` INT NOT NULL,
  `ver_code` VARCHAR(255) NULL,
  `expiry` DATETIME NULL,
  `ver_attempts` INT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_verifications_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `diplomatic_war`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diplomatic_war`.`password_retrieval`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diplomatic_war`.`password_retrieval` ;

CREATE TABLE IF NOT EXISTS `diplomatic_war`.`password_retrieval` (
  `user_id` INT NOT NULL,
  `salt` VARCHAR(255) NULL,
  `retrieval_hash` VARCHAR(255) NULL,
  `expiry` DATETIME NULL,
  `session_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`, `session_id`),
  INDEX `fk_passwordRetrieval_session_idx` (`session_id` ASC),
  CONSTRAINT `fk_passwordRetrieval_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `diplomatic_war`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_passwordRetrieval_session`
    FOREIGN KEY (`session_id`)
    REFERENCES `diplomatic_war`.`sessions` (`session_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

